### ISSUE TITLE
KVM bridge + public ips for vms

### ISSUE THREAD

**Issue by xoraingroup** [goffinet/virt-scripts#4]
Hi,

I have been searching on internet to find a way to assign vms with public ips that i have rented out from ISP (currently Hetzner) in my case. 

I have been using your scripts and they work like a breeze. Really awesome work. Can you provide some tutorial + script which we can use to assign public ips to vms and configure bridge accordingly. 

Your help will be highly appreciated. Kudos to you. :)

**Comment by goffinet** [comment]
Hi,
Thank you very much for your support. I will try to answer your request as soon as possible.
Best regards,

**Comment by xoraingroup** [comment]
Thank you looking forward to hear from you. :)))

**Comment by xoraingroup** [comment]
Any updates on this?

**Comment by goffinet** [comment]
https://github.com/goffinet/virt-scripts/commit/b961a745128b93839cb95ad76834c1621ae2605f
Please see https://github.com/goffinet/virt-scripts/blob/master/README.hetzner.md.
