### ISSUE TITLE
Hello i'm install centos but not find where passwd?

### ISSUE THREAD

**Issue by anhdao1520** [goffinet/virt-scripts#5]
Can you help me?
How to set passwd? or find them?

**Comment by goffinet** [comment]
All published images on "download.goffinet.org/kvm" are built from the project [https://github.com/goffinet/packer-kvm](https://github.com/goffinet/packer-kvm) with Packer. The username and password of these images is in the json file of the distribution name.

For example, for Centos 7 the file [centos7.json at line 15](https://github.com/goffinet/packer-kvm/blob/6e890a28f4b123a36064693f45f68ac17d9c6cd4/centos7.json#L15) is used:

```json
{
    "variables":
    {
      "cpu": "2",
      "ram": "2048",
      "name": "centos",
      "disk_size": "40000",
      "version": "7",
      "iso_checksum_type": "sha256",
      "iso_urls": "http://ftp.belnet.be/mirror/ftp.centos.org/7.8.2003/isos/x86_64/CentOS-7-x86_64-Minimal-2003.iso",
      "iso_checksum": "659691c28a0e672558b003d223f83938f254b39875ee7559d1a4a14c79173193",
      "headless": "true",
      "config_file": "centos7-kickstart.cfg",
      "ssh_username": "root",
      "ssh_password": "testtest",
      "destination_server": "download.goffinet.org"
    }
}
```

If you build the images yourself with this project and the `auto-install.sh`, you will find the passwords in the functions that create the response files, for example at [line 204 of this script](https://github.com/goffinet/virt-scripts/blob/a328d9385d9d3ac1bb9665d014b6573f9fb48a28/auto-install.sh#L204) for Centos 7 :

```
rootpw --plaintext testtest
```

**Comment by goffinet** [comment]
To be clear :

| Distribution | Username | Default Password |
| --- | --- | --- |
| bionic | `root` | `testtest` | 
| focal | `ubuntu` | `ubuntu` | 
| centos7 | `root` | `testtest` | 
| centos8 | `root` | `testtest` | 
| debian10 | `root` | `testtest` | 
| fedora32 | `root` | `testtest` |

**Comment by anhdao1520** [comment]
Sorry, but is there a way to setup static ip for debian virtual machine, when kickstart automatic installing
